### PR TITLE
ColorGradientWidget

### PR DESCRIPTION
**Pull request by mjendruk**
Add `ColorGradientWidget` along with a bunch of improvements to `widgetzeug`.
See widgetexample for usage example.

Edit: I also added the `DataLinkWidget` class and integrated it into the `ColorGradientWidget`.

### CODE REVIEW

**Comment by scheibel** [comment]
The color gradient widget is unusably slow on Ubuntu 14.10 x64 with gcc 4.9.1 and an Nvidia GTX 680 graphics card.
And the widget crashes when switching to fullscreen (or even high resolutions).

**Comment by scheibel** [comment]
Performance is okay now, the bug with the big window size is also gone :+1: 

:ship: (but wait for at least @cgcostume's review)

**Comment by cgcostume** [comment]
since this branch will be used for (its intentional) review and refinement of the color gradient features, please close PR if acceptable and leave branch open.

This branch currently features a complete revised ColorScheme feature, WidgetSettings Controler, the Widget Controler conept by ColorSchemeControlWidget, applied our latest GUI standards/defaults, and  more ...

**Comment by scheibel** [comment]
Works on Linux using gcc.

**Comment by dommueller** [comment]
Works on OS X. :ship:

**Pull request merged**
