### PR TITLE
Add OptionChanged-Signal to AbstractProperty

### PR DESCRIPTION
**Pull request by ldurdel**

### CODE REVIEW

**Comment by scheibel** [comment]
Please merge the current libzeug master.

**Comment by cgcostume** [comment]
:+1: (please update, then merge and close), but wait for ok form @scheibel or @sbusch42

**Comment by sbusch42** [comment]
Do not mix variables between methods. Please add a new public block at the top (for public variables) and put the signal optionChanged there. After that is done and the branch is updated, :shipit:

**Comment by sbusch42** [comment]
Could we please stop *removing* comments? You never know what is obvious for new users, so please document wherever possible instead of avoiding documentation wherever possible. The documentation for the signal was fine, please restore and for the future the aim should be to document every item at least in the public interface.

**Comment by scheibel** [comment]
I had to read your comment about the variables and the according source code four times to recognize you're talking about attributes/members. I wondered where in this really small PR you saw strange placed temporary variables.
Concept naming (especially in C++) is just strange...

**Comment by sbusch42** [comment]
I was talking about the signal "optionChanged", which I clearly stated in my comment ... It is placed in between methods, which is not nice. Public variables (or attributes) deserve an own block.

**Comment by scheibel** [comment]
:shipit: ?
:ship: !

**Comment by mjendruk** [comment]
:shipit:

**Pull request merged**
